# Generated by Django 6.0 on 2026-02-12 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem_fila', models.IntegerField(default=0, help_text='Ordem na fila de plantões')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['ordem_fila', 'nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='EscalaAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True)),
                ('data_inicio', models.DateField()),
                ('semanas_gerar', models.IntegerField(default=4, help_text='Quantas semanas gerar na escala')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('criada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escala Automática',
                'verbose_name_plural': 'Escalas Automáticas',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data do plantão')),
                ('dia_semana', models.CharField(choices=[('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('turno', models.CharField(choices=[('SABADO_TARDE1', 'Sábado 13:00 - 17:00'), ('SABADO_TARDE2', 'Sábado 17:00 - 21:00'), ('DOMINGO_MANHA', 'Domingo 08:00 - 13:00'), ('DOMINGO_TARDE1', 'Domingo 13:00 - 17:00'), ('DOMINGO_TARDE2', 'Domingo 17:00 - 21:00')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantoes', to='plantao.colaborador')),
            ],
            options={
                'verbose_name': 'Plantão',
                'verbose_name_plural': 'Plantões',
                'ordering': ['data', 'hora_inicio'],
                'unique_together': {('data', 'turno')},
            },
        ),
    ]
