# Generated by Django 6.0 on 2026-02-16 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrocaPlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('RECUSADA', 'Recusada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_recebidas', to='plantao.colaborador')),
                ('plantao_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troca_destino', to='plantao.plantao')),
                ('plantao_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troca_origem', to='plantao.plantao')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_solicitadas', to='plantao.colaborador')),
            ],
            options={
                'verbose_name': 'Troca de Plantão',
                'verbose_name_plural': 'Trocas de Plantões',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TROCA_SOLICITADA', 'Solicitação de Troca'), ('TROCA_ACEITA', 'Troca Aceita'), ('TROCA_RECUSADA', 'Troca Recusada'), ('TROCA_CANCELADA', 'Troca Cancelada')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='plantao.colaborador')),
                ('troca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='plantao.trocaplantao')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
