# Generated by Django 6.0 on 2026-02-20 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantao', '0002_trocaplantao_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaAutomaticaTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(help_text='Data do primeiro sábado')),
                ('semanas_gerar', models.IntegerField(default=4)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('criada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escala Automática - Técnico',
                'verbose_name_plural': 'Escalas Automáticas - Técnicos',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='TecnicoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ordem_fila', models.IntegerField(default=0, help_text='Ordem na rotação de plantões')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Técnico de Campo',
                'verbose_name_plural': 'Técnicos de Campo',
                'ordering': ['ordem_fila', 'nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='PlantaoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('SABADO_DUPLA', 'Sábado - Dupla (14:00-18:00)'), ('DOMINGO_SOLO', 'Domingo - Solo (Dia Todo)'), ('AVULSO_SOLO', 'Dia Avulso - Solo (Dia Todo)')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tecnico_dupla', models.ForeignKey(blank=True, help_text='Apenas para plantões de sábado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantoes_dupla', to='plantao.tecnicocampo')),
                ('tecnico_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantoes_principal', to='plantao.tecnicocampo')),
            ],
            options={
                'verbose_name': 'Plantão Técnico',
                'verbose_name_plural': 'Plantões Técnicos',
                'ordering': ['data', 'hora_inicio'],
                'unique_together': {('data', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='TrocaPlantaoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('RECUSADA', 'Recusada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_tecnico_recebidas', to='plantao.tecnicocampo')),
                ('plantao_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troca_tecnico_destino', to='plantao.plantaotecnico')),
                ('plantao_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troca_tecnico_origem', to='plantao.plantaotecnico')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_tecnico_solicitadas', to='plantao.tecnicocampo')),
            ],
            options={
                'verbose_name': 'Troca de Plantão - Técnico',
                'verbose_name_plural': 'Trocas de Plantões - Técnicos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
