# Generated by Django 5.2.13 on 2026-05-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantao', '0003_escalaautomaticatecnico_tecnicocampo_plantaotecnico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantao',
            name='dia_semana',
            field=models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3),
        ),
        migrations.AlterField(
            model_name='plantao',
            name='turno',
            field=models.CharField(choices=[('SABADO_TARDE1', 'Sábado 13:00 – 17:00'), ('SABADO_TARDE2', 'Sábado 17:00 – 21:00'), ('DOMINGO_MANHA', 'Domingo 08:00 – 13:00'), ('DOMINGO_TARDE1', 'Domingo 13:00 – 17:00'), ('DOMINGO_TARDE2', 'Domingo 17:00 – 21:00'), ('AVULSO_MANHA', 'Avulso 08:00 – 13:00'), ('AVULSO_TARDE1', 'Avulso 13:00 – 17:00'), ('AVULSO_TARDE2', 'Avulso 17:00 – 21:00'), ('AVULSO_DIA_TODO', 'Avulso 08:00 – 18:00')], max_length=20),
        ),
    ]
